"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[cmd_duration]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false

[hostname]
disabled = false
ssh_only = false

[rlang]
disabled = true

[username]
show_always = true
